version: '3.8'
services:
  web-profile-be:
    restart: always
    build: .
    container_name: web-profile-be
    ports:
      - 8000:8000
    networks:
      - app
    env_file:
      - .env
networks:
  app:
    driver: bridge
