version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=ianfebi01
      - POSTGRES_PASSWORD=jenengmu
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  web-profile-be:
    restart: always
    build: .
    container_name: web-profile-be
    ports:
      - 8000:8000
    networks:
      - app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

networks:
  app:
    driver: bridge
volumes:
  postgres:
